### ISSUE TITLE
Coldbox breaking updates

### ISSUE THREAD

**Issue by msis-adrian** [elpete/whoops#14]
FYI, starting at **Coldbox 6.2.0-snapshot**.... the following error will start to occur.
```

No matching function [PROCESSSTACKTRACE] found

\modules\whoops\views\whoops.cfm: line 276
\coldbox\system\Bootstrap.cfc: line 646
\coldbox\system\Bootstrap.cfc: line 395
\coldbox\system\Bootstrap.cfc: line 483
\Application.cfc: line 40
```

Now that whoops is in maintenance mode, but integrated into CB 6, I just thought maybe by leaving this information here people will find it useful to know that **CB 6.1.0+1309** is the last working version for this module.

For documentation purposes by having this issue opened and then even if closed immediately, people can find it when trying to diagnose their error.

I really like the style of the full version ;)

**Comment by Adrian-Sanchez** [comment]
Updated: It's not a Coldbox issue. It's some sort of scope issue.
